import Head from "next/head";
import styles from "../styles/Home.module.css";
import SearchBox from "../components/SearchBox";
import "react-loading-skeleton/dist/skeleton.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/img/united-kingdom.png" />
      </Head>
      <main className={styles.main}>
        <div className="h-[95vh] flex flex-col justify-center">
          <div className="flex justify-center items-center flex-col mb-8">
            <img
              src="/assets/img/Eng (2).png"
              className="mb-4 md:mb-8 w-[90px] md:w-[200px]"
            />
            <h1 className="font-[Quicksand bold] font-bold text-3xl md:text-5xl">
              English Dictionary
            </h1>
          </div>
          <SearchBox />
        </div>
      </main>
    </>
  );
}
