import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { Provider, useDispatch, useSelector } from "react-redux";
import WordService from "../Service/Word";
import axios from "axios";
import { useState } from "react";
import SearchBox from "../components/SearchBox";
import mainImg from "../public/img/main-1.jpg";
import Skeleton from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const dispatch = useDispatch()
  // const get = new WordService(axios)
  // const [word, setword] = useState('');
  // const change = (e:any) => setword(e.target.value)

  return (
    <>
      <Head>
        <title>Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="h-[95vh]">
          <SearchBox />
        </div>
      </main>
    </>
  );
}
